export const STATES = [
  { code: "AL", name: "Alabama",        agency: "Alabama Dept. of Public Health",                    url: "https://www.alabamapublichealth.gov/ruralhealth/" },
  { code: "AK", name: "Alaska",         agency: "Alaska Dept. of Health",                            url: "https://health.alaska.gov/en/education/rural-health-transformation-program/" },
  { code: "AZ", name: "Arizona",        agency: "Arizona AHCCCS / ADHS",                             url: "https://azgovernor.gov/" },
  { code: "AR", name: "Arkansas",       agency: "Arkansas Dept. of Finance & Admin",                 url: "https://governor.arkansas.gov/arkansas-rural-health-transformation-program-application/" },
  { code: "CA", name: "California",     agency: "CA Dept. of Health Care Access & Information",      url: "https://hcai.ca.gov/workforce/health-workforce/california-state-office-of-rural-health/" },
  { code: "CO", name: "Colorado",       agency: "CO Dept. of Health Care Policy & Financing",        url: "https://hcpf.colorado.gov/rural-health-transformation-program" },
  { code: "CT", name: "Connecticut",    agency: "Connecticut Dept. of Social Services",              url: "https://www.ruralhealthct.org/" },
  { code: "DE", name: "Delaware",       agency: "Delaware DHSS / Division of Public Health",         url: "https://news.delaware.gov/" },
  { code: "FL", name: "Florida",        agency: "Florida Agency for Health Care Administration",     url: "https://ahca.myflorida.com/rural-health-transformation-program" },
  { code: "GA", name: "Georgia",        agency: "Georgia Dept. of Community Health",                 url: "https://dch.georgia.gov/great-health-program-georgias-rural-health-transformation-program" },
  { code: "HI", name: "Hawaii",         agency: "State of Hawaii RHTP Oversight Team",               url: "https://health.hawaii.gov/" },
  { code: "ID", name: "Idaho",          agency: "Idaho Dept. of Health and Welfare",                 url: "https://healthandwelfare.idaho.gov/providers/rural-health-transformation-program-grant/" },
  { code: "IL", name: "Illinois",       agency: "Illinois Dept. of Healthcare & Family Services",    url: "https://hfs.illinois.gov/info/fedresctr/ruralhealthtp.html" },
  { code: "IN", name: "Indiana",        agency: "Indiana FSSA / IDOH",                               url: "https://www.in.gov/doh/" },
  { code: "IA", name: "Iowa",           agency: "Iowa Dept. of Health and Human Services",           url: "https://hhs.iowa.gov/initiatives/healthy-hometowns-iowas-rural-health-transformation-plan" },
  { code: "KS", name: "Kansas",         agency: "Kansas Dept. of Health and Environment",            url: "https://www.kdhe.ks.gov/" },
  { code: "KY", name: "Kentucky",       agency: "Kentucky Cabinet for Health & Family Services",     url: "https://chfs.ky.gov/" },
  { code: "LA", name: "Louisiana",      agency: "Louisiana Dept. of Health",                         url: "https://ldh.la.gov/" },
  { code: "ME", name: "Maine",          agency: "Maine Dept. of Health and Human Services",          url: "https://www.maine.gov/dhhs/" },
  { code: "MD", name: "Maryland",       agency: "Maryland Dept. of Health",                          url: "https://health.maryland.gov/" },
  { code: "MA", name: "Massachusetts",  agency: "MA Exec. Office of Health & Human Services",        url: "https://www.mass.gov/rural-health" },
  { code: "MI", name: "Michigan",       agency: "Michigan DHHS",                                     url: "https://www.michigan.gov/mdhhs/" },
  { code: "MN", name: "Minnesota",      agency: "Minnesota Dept. of Health",                         url: "https://www.health.state.mn.us/" },
  { code: "MS", name: "Mississippi",    agency: "Mississippi State Dept. of Health",                 url: "https://msdh.ms.gov/" },
  { code: "MO", name: "Missouri",       agency: "Missouri DSS / DHSS",                               url: "https://health.mo.gov/" },
  { code: "MT", name: "Montana",        agency: "Montana DPHHS",                                     url: "https://dphhs.mt.gov/" },
  { code: "NE", name: "Nebraska",       agency: "Nebraska DHHS",                                     url: "https://dhhs.ne.gov/" },
  { code: "NV", name: "Nevada",         agency: "Nevada DHHS",                                       url: "https://dhhs.nv.gov/" },
  { code: "NH", name: "New Hampshire",  agency: "New Hampshire DHHS",                                url: "https://www.dhhs.nh.gov/" },
  { code: "NJ", name: "New Jersey",     agency: "New Jersey Dept. of Health",                        url: "https://www.nj.gov/health/" },
  { code: "NM", name: "New Mexico",     agency: "New Mexico Health Care Authority",                  url: "https://www.hca.nm.gov/rural-health-transformation-program/" },
  { code: "NY", name: "New York",       agency: "New York State Dept. of Health",                    url: "https://www.health.ny.gov/" },
  { code: "NC", name: "North Carolina", agency: "NC DHHS Office of Rural Health",                    url: "https://www.ncdhhs.gov/divisions/office-rural-health/rural-health-transformation-program" },
  { code: "ND", name: "North Dakota",   agency: "North Dakota HHS",                                  url: "https://www.hhs.nd.gov/rural-health-transformation" },
  { code: "OH", name: "Ohio",           agency: "Ohio Dept. of Medicaid / Dept. of Health",          url: "https://medicaid.ohio.gov/" },
  { code: "OK", name: "Oklahoma",       agency: "Oklahoma State Dept. of Health",                    url: "https://www.health.ok.gov/" },
  { code: "OR", name: "Oregon",         agency: "Oregon Health Authority",                           url: "https://www.oregon.gov/oha/" },
  { code: "PA", name: "Pennsylvania",   agency: "Pennsylvania Dept. of Human Services",              url: "https://www.dhs.pa.gov/" },
  { code: "RI", name: "Rhode Island",   agency: "Rhode Island Dept. of Health",                      url: "https://health.ri.gov/" },
  { code: "SC", name: "South Carolina", agency: "South Carolina DHHS",                               url: "https://www.scdhhs.gov/" },
  { code: "SD", name: "South Dakota",   agency: "South Dakota Dept. of Health",                      url: "https://doh.sd.gov/" },
  { code: "TN", name: "Tennessee",      agency: "Tennessee Dept. of Health",                         url: "https://www.tn.gov/health/" },
  { code: "TX", name: "Texas",          agency: "Texas Health and Human Services Commission",        url: "https://www.hhs.texas.gov/" },
  { code: "UT", name: "Utah",           agency: "Utah DHHS",                                         url: "https://health.utah.gov/" },
  { code: "VT", name: "Vermont",        agency: "Vermont Agency of Human Services",                  url: "https://humanservices.vermont.gov/" },
  { code: "VA", name: "Virginia",       agency: "Virginia Dept. of Medical Assistance Services",     url: "https://www.dmas.virginia.gov/" },
  { code: "WA", name: "Washington",     agency: "Washington Health Care Authority",                  url: "https://www.hca.wa.gov/" },
  { code: "WV", name: "West Virginia",  agency: "West Virginia Dept. of Health",                     url: "https://dhhr.wv.gov/" },
  { code: "WI", name: "Wisconsin",      agency: "Wisconsin Dept. of Health Services",                url: "https://www.dhs.wisconsin.gov/" },
  { code: "WY", name: "Wyoming",        agency: "Wyoming Dept. of Health",                           url: "https://health.wyo.gov/" },
];

export const FY26_AWARDS = {
  AL:203404327, AK:272174856, AZ:166988956, AR:208779396, CA:233639308,
  CO:200105604, CT:154249106, DE:157394964, FL:209938195, GA:218862170,
  HI:188892440, ID:185974368, IL:193418216, IN:206927897, IA:209040064,
  KS:221898008, KY:212905591, LA:208374448, ME:190008051, MD:168180838,
  MA:162005238, MI:173128201, MN:193090618, MS:205907220, MO:216276818,
  MT:233509359, NE:218529075, NV:179931608, NH:204016550, NJ:147250806,
  NM:211484741, NY:212058208, NC:213008356, ND:198936970, OH:202030262,
  OK:223476949, OR:197271578, PA:193294054, RI:156169931, SC:200030252,
  SD:189477607, TN:206888882, TX:281319361, UT:195743566, VT:195053740,
  VA:189544888, WA:181257515, WV:199476099, WI:203670005, WY:205004743,
};

export const PHASE_COLORS = {
  Planning:       "#8b5cf6",
  Procurement:    "#f59e0b",
  Implementation: "#10b981",
  Reporting:      "#3b82f6",
};

export const RFP_COLORS = {
  "Active RFPs/RFAs open":         "#10b981",
  "RFPs announced but not open":   "#f59e0b",
  "No active RFPs found":          "#6b7280",
  "Unknown":                       "#4b5563",
};

export const fmt = (n) => "$" + (n / 1e6).toFixed(1) + "M";
